(define (unit1 proc res)
  (equal? (eval proc (interaction-environment)) res))

(define (tests list)
  (if (null? list)
      (display 'tests_ok)
      (let* ((test (car list))
             (proc (car test))
             (res  (cadr test)))
        (display proc)
        (display " -> ")
        (display res)
        (display " : ")
        (display (unit1 proc res))
        (newline)
        (tests (cdr list)))))